Repository TravelWithMeProject/GoWithMe_Server, pull requests merged in 2022-02, with the labels that each got.

#40 PostContent Entity, VO 구현 및 단위 테스트 진행
  src/main/java/team/backend/goWithMe/domain/postcontent/domain/persist/Category.java
  src/main/java/team/backend/goWithMe/domain/postcontent/domain/persist/PostContent.java
  src/main/java/team/backend/goWithMe/domain/postcontent/domain/persist/PostContentRepository.java
  src/main/java/team/backend/goWithMe/domain/postcontent/domain/vo/Content.java
  src/main/java/team/backend/goWithMe/domain/postcontent/domain/vo/Count.java
  src/main/java/team/backend/goWithMe/domain/postcontent/domain/vo/Title.java
  src/test/java/team/backend/goWithMe/domain/postcontent/domain/persist/PostContentTest.java
  src/test/java/team/backend/goWithMe/domain/postcontent/domain/util/PostContentBuilder.java
Labels: Entity, VO

#43 Feat.#031 authentication
  settings.gradle
  src/main/java/team/backend/goWithMe/domain/auth/details/CustomMemberDetailService.java
  src/main/java/team/backend/goWithMe/domain/mate/domain/persist/Mate.java
  src/main/java/team/backend/goWithMe/domain/member/api/MemberManagementController.java
  src/main/java/team/backend/goWithMe/domain/member/application/MemberManagementService.java
  src/main/java/team/backend/goWithMe/domain/member/domain/persist/MemberRepository.java
  src/main/java/team/backend/goWithMe/domain/member/dto/AccessTokenRequestDTO.java
  src/main/java/team/backend/goWithMe/domain/member/dto/MemberUpdateDTO.java
  src/main/java/team/backend/goWithMe/domain/trip/domain/vo/SchedulePeriod.java
  src/main/java/team/backend/goWithMe/domain/trip/domain/vo/ScheduleTitle.java
  src/main/java/team/backend/goWithMe/domain/trip/domain/vo/TimeTableName.java
  src/main/java/team/backend/goWithMe/domain/trip/domain/vo/TimeTablePeriod.java
  src/main/java/team/backend/goWithMe/domain/trip/error/SchedulePeriodInvalidException.java
  src/main/java/team/backend/goWithMe/domain/trip/error/ScheduleTitleInvalidException.java
  src/main/java/team/backend/goWithMe/domain/trip/error/TimeTableNameInvalidException.java
  src/main/java/team/backend/goWithMe/domain/trip/error/TimeTablePeriodInvalidException.java
  src/main/java/team/backend/goWithMe/global/common/AccessToken.java
  src/main/java/team/backend/goWithMe/global/common/RefreshToken.java
  src/main/java/team/backend/goWithMe/global/config/QueryDslConfig.java
  src/main/java/team/backend/goWithMe/global/config/SecurityConfig.java
  src/main/java/team/backend/goWithMe/global/error/exception/ErrorCode.java
Labels: Security, authentication, hotfix, Service

#47 Trip API SPEC 작성 완료
  docs/trip/TripAPI_SPEC.md
Labels: documentation
